** 38399: Nullam sollicitudin suscipit				  :tag1:tag3:
   :PROPERTIES:
   :property1: value1
   :property2: value2
   :END:
   velit. Nullam sollicitudin suscipit urna ut placerat. Nam massa velit,
   dignissim vitae mattis et, laoreet non sapien. Donec ut nisi a arcu
   iaculis porttitor ut in nisl. Morbi gravida sem vel tellus aliquam

** 38400: Fullam exorbitus scribit				  :tag2:tag4:
   SCHEDULED: <2013-10-21 Mon>
    iaculis porttitor ut in nisl. Morbi gravida sem vel tellus aliquam
    accumsan. Maecenas consectetur porta magna at interdum.
   velit. Nullam sollicitudin suscipit urna ut placerat. Nam massa velit,
   dignissim vitae mattis et, laoreet non sapien. Donec ut nisi a arcu
   iaculis porttitor ut in nisl. Morbi gravida sem vel tellus aliquam

** 38401: vitae mattis et							  :tag2:tag4:
   SCHEDULED: <2013-10-25 Thu 15:00>
    accumsan. Maecenas consectetur porta magna at interdum.
   velit. Nullam sollicitudin suscipit urna ut placerat. Nam massa velit,
   dignissim vitae mattis et, laoreet non sapien. Donec ut nisi a arcu
   iaculis porttitor ut in nisl. Morbi gravida sem vel tellus aliquam

** 38402: dignissim vitae mattis et							  :tag2:tag4:
   DEADLINE: <2013-11-30 Sat>
    accumsan. Maecenas consectetur porta magna at interdum.
   velit. Nullam sollicitudin suscipit urna ut placerat. Nam massa velit,
   dignissim vitae mattis et, laoreet non sapien. Donec ut nisi a arcu
   iaculis porttitor ut in nisl. Morbi gravida sem vel tellus aliquam
